module.exports = {
  name: "History",
  qualifications: [
    "A-level Classics",
    "A-level Ancient History",
    "A-level Classical Civilisation",
    "A-level English",
    "A-level Politics",
    "A-level History",
    "A-level Humanities",
    "A-level Psychology",
    "A-level Religious Studies",
    "A-level Humanities",
    "A-level Sociology",
    "BA History",
    "MA History",
    "BA American History",
    "MA American History",
    "BA Economics",
    "MA Economics",
    "BA Economic History",
    "BA European History",
    "BA Modern History",
    "BA Modern European History",
    "BA Archaeology",
    "BA History Studies",
    "BA History of Art",
    "GCSE History"
  ]
}
